// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: phase_a.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//Proposer sends to acceptors Prepare message in first phase of protocol.
type Prepare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Key of value in proposal.
	ProposalKey string `protobuf:"bytes,1,opt,name=proposal_key,json=proposalKey,proto3" json:"proposal_key,omitempty"`
	//Version of updating.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Prepare) Reset() {
	*x = Prepare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_a_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepare) ProtoMessage() {}

func (x *Prepare) ProtoReflect() protoreflect.Message {
	mi := &file_phase_a_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepare.ProtoReflect.Descriptor instead.
func (*Prepare) Descriptor() ([]byte, []int) {
	return file_phase_a_proto_rawDescGZIP(), []int{0}
}

func (x *Prepare) GetProposalKey() string {
	if x != nil {
		return x.ProposalKey
	}
	return ""
}

func (x *Prepare) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

//Acceptor responses to Proposer by sending Promise.
type Promise struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Accepted or not by acceptor.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	//Key of value in proposal.
	ProposalKey string `protobuf:"bytes,2,opt,name=proposal_key,json=proposalKey,proto3" json:"proposal_key,omitempty"`
	//Version of updating.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Promise) Reset() {
	*x = Promise{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_a_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Promise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promise) ProtoMessage() {}

func (x *Promise) ProtoReflect() protoreflect.Message {
	mi := &file_phase_a_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promise.ProtoReflect.Descriptor instead.
func (*Promise) Descriptor() ([]byte, []int) {
	return file_phase_a_proto_rawDescGZIP(), []int{1}
}

func (x *Promise) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Promise) GetProposalKey() string {
	if x != nil {
		return x.ProposalKey
	}
	return ""
}

func (x *Promise) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_phase_a_proto protoreflect.FileDescriptor

var file_phase_a_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x68, 0x61, 0x73, 0x65, 0x5f, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x22, 0x46, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x62,
	0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x61, 0x6c, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x32, 0x37, 0x0a, 0x06, 0x50, 0x68, 0x61, 0x73, 0x65, 0x41, 0x12, 0x2d, 0x0a, 0x0b,
	0x73, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x0e, 0x2e, 0x70, 0x61,
	0x78, 0x6f, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x1a, 0x0e, 0x2e, 0x70, 0x61,
	0x78, 0x6f, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x70,
	0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_phase_a_proto_rawDescOnce sync.Once
	file_phase_a_proto_rawDescData = file_phase_a_proto_rawDesc
)

func file_phase_a_proto_rawDescGZIP() []byte {
	file_phase_a_proto_rawDescOnce.Do(func() {
		file_phase_a_proto_rawDescData = protoimpl.X.CompressGZIP(file_phase_a_proto_rawDescData)
	})
	return file_phase_a_proto_rawDescData
}

var file_phase_a_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_phase_a_proto_goTypes = []interface{}{
	(*Prepare)(nil), // 0: paxos.Prepare
	(*Promise)(nil), // 1: paxos.Promise
}
var file_phase_a_proto_depIdxs = []int32{
	0, // 0: paxos.PhaseA.sendPrepare:input_type -> paxos.Prepare
	1, // 1: paxos.PhaseA.sendPrepare:output_type -> paxos.Promise
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_phase_a_proto_init() }
func file_phase_a_proto_init() {
	if File_phase_a_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phase_a_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prepare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phase_a_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Promise); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phase_a_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_phase_a_proto_goTypes,
		DependencyIndexes: file_phase_a_proto_depIdxs,
		MessageInfos:      file_phase_a_proto_msgTypes,
	}.Build()
	File_phase_a_proto = out.File
	file_phase_a_proto_rawDesc = nil
	file_phase_a_proto_goTypes = nil
	file_phase_a_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PhaseAClient is the client API for PhaseA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhaseAClient interface {
	//Proposer sends Prepare to acceptor and gets Promise as response.
	SendPrepare(ctx context.Context, in *Prepare, opts ...grpc.CallOption) (*Promise, error)
}

type phaseAClient struct {
	cc grpc.ClientConnInterface
}

func NewPhaseAClient(cc grpc.ClientConnInterface) PhaseAClient {
	return &phaseAClient{cc}
}

func (c *phaseAClient) SendPrepare(ctx context.Context, in *Prepare, opts ...grpc.CallOption) (*Promise, error) {
	out := new(Promise)
	err := c.cc.Invoke(ctx, "/paxos.PhaseA/sendPrepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhaseAServer is the server API for PhaseA service.
type PhaseAServer interface {
	//Proposer sends Prepare to acceptor and gets Promise as response.
	SendPrepare(context.Context, *Prepare) (*Promise, error)
}

// UnimplementedPhaseAServer can be embedded to have forward compatible implementations.
type UnimplementedPhaseAServer struct {
}

func (*UnimplementedPhaseAServer) SendPrepare(context.Context, *Prepare) (*Promise, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPrepare not implemented")
}

func RegisterPhaseAServer(s *grpc.Server, srv PhaseAServer) {
	s.RegisterService(&_PhaseA_serviceDesc, srv)
}

func _PhaseA_SendPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Prepare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhaseAServer).SendPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxos.PhaseA/SendPrepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhaseAServer).SendPrepare(ctx, req.(*Prepare))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhaseA_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.PhaseA",
	HandlerType: (*PhaseAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendPrepare",
			Handler:    _PhaseA_SendPrepare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phase_a.proto",
}
