// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: phase_b.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//Proposer sends Accept message to acceptors in second phase of protocol.
type Accept struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Key of value in proposal.
	ProposalKey string `protobuf:"bytes,1,opt,name=proposal_key,json=proposalKey,proto3" json:"proposal_key,omitempty"`
	//Value of proposal.
	ProposalValue string `protobuf:"bytes,2,opt,name=proposal_value,json=proposalValue,proto3" json:"proposal_value,omitempty"`
	//Version of updating.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Accept) Reset() {
	*x = Accept{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_b_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Accept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accept) ProtoMessage() {}

func (x *Accept) ProtoReflect() protoreflect.Message {
	mi := &file_phase_b_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accept.ProtoReflect.Descriptor instead.
func (*Accept) Descriptor() ([]byte, []int) {
	return file_phase_b_proto_rawDescGZIP(), []int{0}
}

func (x *Accept) GetProposalKey() string {
	if x != nil {
		return x.ProposalKey
	}
	return ""
}

func (x *Accept) GetProposalValue() string {
	if x != nil {
		return x.ProposalValue
	}
	return ""
}

func (x *Accept) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

//Acceptor responses to proposer with this message.
type Accepted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Accepted or not.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *Accepted) Reset() {
	*x = Accepted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_b_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Accepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accepted) ProtoMessage() {}

func (x *Accepted) ProtoReflect() protoreflect.Message {
	mi := &file_phase_b_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accepted.ProtoReflect.Descriptor instead.
func (*Accepted) Descriptor() ([]byte, []int) {
	return file_phase_b_proto_rawDescGZIP(), []int{1}
}

func (x *Accepted) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_phase_b_proto protoreflect.FileDescriptor

var file_phase_b_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x68, 0x61, 0x73, 0x65, 0x5f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x22, 0x6c, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c,
	0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x26, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x32, 0x36, 0x0a, 0x06,
	0x50, 0x68, 0x61, 0x73, 0x65, 0x42, 0x12, 0x2c, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x2e, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x65, 0x64, 0x42, 0x05, 0x5a, 0x03, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_phase_b_proto_rawDescOnce sync.Once
	file_phase_b_proto_rawDescData = file_phase_b_proto_rawDesc
)

func file_phase_b_proto_rawDescGZIP() []byte {
	file_phase_b_proto_rawDescOnce.Do(func() {
		file_phase_b_proto_rawDescData = protoimpl.X.CompressGZIP(file_phase_b_proto_rawDescData)
	})
	return file_phase_b_proto_rawDescData
}

var file_phase_b_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_phase_b_proto_goTypes = []interface{}{
	(*Accept)(nil),   // 0: paxos.Accept
	(*Accepted)(nil), // 1: paxos.Accepted
}
var file_phase_b_proto_depIdxs = []int32{
	0, // 0: paxos.PhaseB.sendAccept:input_type -> paxos.Accept
	1, // 1: paxos.PhaseB.sendAccept:output_type -> paxos.Accepted
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_phase_b_proto_init() }
func file_phase_b_proto_init() {
	if File_phase_b_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phase_b_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Accept); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phase_b_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Accepted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phase_b_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_phase_b_proto_goTypes,
		DependencyIndexes: file_phase_b_proto_depIdxs,
		MessageInfos:      file_phase_b_proto_msgTypes,
	}.Build()
	File_phase_b_proto = out.File
	file_phase_b_proto_rawDesc = nil
	file_phase_b_proto_goTypes = nil
	file_phase_b_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PhaseBClient is the client API for PhaseB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhaseBClient interface {
	//Proposer sends Accept to acceptor and gets Accepted as response.
	SendAccept(ctx context.Context, in *Accept, opts ...grpc.CallOption) (*Accepted, error)
}

type phaseBClient struct {
	cc grpc.ClientConnInterface
}

func NewPhaseBClient(cc grpc.ClientConnInterface) PhaseBClient {
	return &phaseBClient{cc}
}

func (c *phaseBClient) SendAccept(ctx context.Context, in *Accept, opts ...grpc.CallOption) (*Accepted, error) {
	out := new(Accepted)
	err := c.cc.Invoke(ctx, "/paxos.PhaseB/sendAccept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhaseBServer is the server API for PhaseB service.
type PhaseBServer interface {
	//Proposer sends Accept to acceptor and gets Accepted as response.
	SendAccept(context.Context, *Accept) (*Accepted, error)
}

// UnimplementedPhaseBServer can be embedded to have forward compatible implementations.
type UnimplementedPhaseBServer struct {
}

func (*UnimplementedPhaseBServer) SendAccept(context.Context, *Accept) (*Accepted, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAccept not implemented")
}

func RegisterPhaseBServer(s *grpc.Server, srv PhaseBServer) {
	s.RegisterService(&_PhaseB_serviceDesc, srv)
}

func _PhaseB_SendAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Accept)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhaseBServer).SendAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paxos.PhaseB/SendAccept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhaseBServer).SendAccept(ctx, req.(*Accept))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhaseB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paxos.PhaseB",
	HandlerType: (*PhaseBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendAccept",
			Handler:    _PhaseB_SendAccept_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phase_b.proto",
}
